<a href="https://colab.research.google.com/github/Shuaib11-Github/CodeHub/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.5


In [7]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [8]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
b = np.arange(0, 10)
print(type(b))
print(b.dtype)

<class 'numpy.ndarray'>
int64


In [10]:
b.ndim

1

In [11]:
b.itemsize

8

In [12]:
b.nbytes

80

In [14]:
c = np.zeros(10)
c[4] = 1
c

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [16]:
d = np.arange(10, 50)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
d[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [20]:
x = np.arange(0, 9)
x.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
y = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(y)

(array([0, 1, 4]),)

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

OR

In [23]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
z = np.random.random((3, 3, 3))
z

array([[[0.63293918, 0.33322448, 0.00653193],
        [0.57457999, 0.84388967, 0.69778383],
        [0.06639604, 0.75979702, 0.97240954]],

       [[0.02728707, 0.20675596, 0.93257439],
        [0.03938638, 0.38825666, 0.05829881],
        [0.03130772, 0.48800614, 0.00643113]],

       [[0.26645846, 0.953512  , 0.06821116],
        [0.77711461, 0.13219001, 0.71521594],
        [0.33933285, 0.00467973, 0.45440275]]])

In [31]:
e = np.random.random((10, 10))
print(e.min())
print(e.max())

### OR

print(np.min(e))
print(np.max(e))

0.016016675881075026
0.9985504560688291
0.016016675881075026
0.9985504560688291


In [33]:
f = np.random.random((5, 6))
print(np.mean(f))

### OR

print(f.mean())

0.5025541021543404
0.5025541021543404


In [35]:
g = np.ones((5, 5))
g[1:4, 1:4] = 0
g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
h = np.ones((5, 5))
h[:1, :] = 0
h[:, :1] = 0
h[:, -1] = 0
h[-1, :] = 0
print(h)

### OR

h = np.ones((5,5))
h[:1, :] = 0
h[:, :1] = 0
h[4:, :] = 0
h[:, 4:] = 0

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [56]:
i = np.arange(1,15).reshape(2,7)
print(i[1, 5])
print(i[:1, :])
print(i[:, 2])
print(i[:1, 1::2])
i[1, 5] = 20
print(i[1, 5])

### OR

i = np.arange(1,15).reshape(2,7)
# To get 13
print(i[1,5])
# To get first row only
print(i[0,:])
# to get third column only
print(i[:,2])
# To get [2, 4, 6]
print(i[0,1::2])
# replace 13 by 20
i[1,5] = 20
print(i)

13
[[1 2 3 4 5 6 7]]
[ 3 10]
[[2 4 6]]
20


In [62]:
j  =np.arange(1, 17)
print(j.ndim)
print(j.reshape(2, 8))

### OR

j = np.arange(1,17)
# Dimension of j
print(j.ndim)
# convert 1D to 2D
print(j.reshape((2,8)))

1
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
1
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [63]:
a = np.array([1,2,3])
np.append(np.repeat(a,3), np.tile(a, 3))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [79]:
l = range(100)
a = 100
import sys
sys.getsizeof(a) * len(l)

2800

In [80]:
a1 = np.arange(100)
a1.size * a1.itemsize

800

In [71]:
import time
import sys
### List
size = 10000000
l1 = range(size)
l2 = range(size)
start = time.time()
a = [(x * y) for x, y in zip(l1, l2) ]
print('Time taken by List: ', (time.time() - start), 'Seconds')

### Numpy Array
n1 = np.arange(size)
n2 = np.arange(size)
start1 = time.time()
b = n1 * n2
print('Time taken by Numpy array: ', (time.time() - start1), 'Seconds')

Time taken by List:  1.261040210723877 Seconds
Time taken bu Numpy array:  0.02216196060180664 Seconds
